### ISSUE TITLE
oversaturation of IF images

### ISSUE THREAD

**Issue by StefanosVoglis** [BodenmillerGroup/napari-czifile2#6] opened 2022-02-02 17:51 UTC
Problem of oversaturation in IF channels occurs with napari v. 0.4.12 + immucan-roi v.0.1.0 + napari-cfzifile2 0.2.5

as a workaround: downgrading napari-cfzifile2 to 0.2.3, then it works fine.

**Comment by jwindhager** [comment] 2022-02-04 09:33
Duplicate of #5

**Closed by jwindhager** 2022-02-04 09:33 UTC
Labels: bug
